# Site settings
title: Cemosis
encoding:utf8
email: contact@cemosis.fr
description: >
              Cemosis, le Centre de Modélisation et de Simulation de Strasbourg, est une structure à
              l'interface avec les disciplines et les entreprises nécessitant la modélisation et la
              simulation numérique.

url: "http://www.cemosis.fr/" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

kramdown:
    parse_block_html: true
    parse_span_html: true

paginate: 5

paginate_path: /news_/page:num/

highlighter: pygments

permalink: pretty

timezone: Europe/Paris
future: true
lsi: false

gems: [jekyll-paginate]
#gems:
#  - octopress-date-format

scholar:
  style: apa
  locale: en
  
  sort_by: none
  order: descending
  
  source: ./_bibliography
  bibliography: cemosis.bib
  bibliography_template: "{{reference}}"
  
  replace_strings: true
  join_strings:    true
  
  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"
